server:
  port: 8082

logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN
    com:
      springsecurity:
        demo: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost/login?useSSL=false
    username: newUser
    password: serife
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: testspring456@gmail.com
    password: Really1234
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
